### ISSUE TITLE
[Pre-Release 0.6] Floating leaf blocks in midair

### ISSUE THREAD

**Issue by ghost** [codingminecraft/StreamMinecraftClone#11]
When loading in a new world, leaf blocks that are connected to nothing are being generated

1. Create a new world
2. Look around for a while

I believe that those leaf blocks should have been turned into a tree or either that they shouldn't have been generated at all

https://user-images.githubusercontent.com/86744385/147682745-ec1154d0-fb79-4cf8-ad2c-94c6e4e521fe.png

I am currently using Windows 10 Home (21H2).

**Comment by codingminecraft** [comment]
Thanks for bringing this issue to my attention, I'll make sure to have it fixed in the next release 😄

**Comment by ghost** [comment]
NOTE: This problem seems to be fixed in the Pre-Release 0.7
