### ISSUE TITLE
rand() is very slow, prefer using something else

### ISSUE THREAD

**Issue by GeorgeAzma** [codingminecraft/StreamMinecraftClone#18]
rand is slow, unreliable and only supports x16 bit numbers, it's used in chunk gen code, which is usually critical part (performance wise). I have a very good rng which should be ~15x faster, reliable and supports x64 bit (best from all the rngs I tested), I will put the code tomorrow here. (It's late)

**Comment by codingminecraft** [comment]
Is it tomorrow yet? I'm interested in what you have haha

**Comment by GeorgeAzma** [comment]
Oh yeah sorry, I was busy, wait a sec

**Comment by GeorgeAzma** [comment]
here (added some comments for you which you can delete):
```
#pragma once

class RNG 
{
public:
	static inline uint64_t seed = 3773452183ULL; //Nothing special just a random number

public:
	static double Float()
	{
		return (double)next() / max();
	}
	static uint64_t Uint()
	{
		return next();
	}
	static int64_t Int()
	{
		return next();
	}
	static bool Bool()
	{
		return next() >> 63ULL; //Not sure if this is the fastest method to extract bool from random int (maybe do: num & 1)
	}
	static glm::vec3 Vec3() //TODO: Replace glm::vec3 with your vec3 type
	{
		float theta = Float() * 6.283185307179586476925286766559f;
		float phi = std::acos(Float() * 2 - 1);

		float x = std::sin(phi) * std::cos(theta);
		float y = std::sin(phi) * std::sin(theta);
		float z = std::cos(phi);

		return glm::vec3(x, y, z);
	}
	static glm::vec2 Vec2() //TODO: Replace glm::vec2 with your vec2 type
	{
		float theta = Float() * 6.283185307179586476925286766559f;

		return glm::vec2(cos(theta), sin(theta));
	}
	static constexpr uint64_t max()
	{
		return std::numeric_limits<uint64_t>::max();
	}
	static constexpr uint64_t min()
	{
		return std::numeric_limits<uint64_t>::min();
	}

private:
	static uint64_t next()
	{
		uint64_t z = (seed += 0x9E3779B97F4A7C15ULL);
		z = (z ^ (z >> 30)) * 0xBF58476D1CE4E5B9ULL;
		z = (z ^ (z >> 27)) * 0x94D049BB133111EBULL;
		return z ^ (z >> 31);
	}
};
```

**Comment by GeorgeAzma** [comment]
I don't remeber name of rng you can find it on internet if you'd like

**Comment by GeorgeAzma** [comment]
I can give more stuff, if I look at the code sometime (I love Minecraft clones lol)

**Comment by codingminecraft** [comment]
From what I found on the internet it looks like you're using splitmix64, which is about 4x faster than C's random function (according to the same source I found haha). I'll go ahead and add this to my closed source version. I had been planning to switch away from the standard C rand() function and it slipped my mind. Thanks for the input!

**Comment by codingminecraft** [comment]
I haven't gotten a chance to try it out yet haha. I can comment on this thread with the performance difference once I get a chance to test it if you're interested :)

**Comment by GeorgeAzma** [comment]
Yes, thank you
