### ISSUE TITLE
when i launch the game almost all of the textures are missing and i dont really like that please fix that all the textures are black for me

### ISSUE THREAD

**Issue by 6AMer** [codingminecraft/StreamMinecraftClone#19]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS, Linux]

**Additional context**

**Comment by codingminecraft** [comment]
Please fill out the bug report form. I can't begin to debug this until I have much more information and the error log. I'll be closing this for now.

**Comment by 6AMer** [comment]
here you go look this happens to me

2022-07-20, tr, 14:20 codingminecraft ***@***.***> rašė:

**Comment by 6AMer** [comment]
could you please send me a fix or a 32bit version because i have 32bit
windows 10 pro so please i really want to play crumble


2022-07-20, tr, 14:50 Arentas Daraska ***@***.***> rašė:
