### ISSUE TITLE
Makefile

### ISSUE THREAD

**Issue by meisme-dev** [codingminecraft/StreamMinecraftClone#4]
Add a makefile or something

**Comment by codingminecraft** [comment]
I use premake to generate project files. Run:
`build.bat gmake`
to generate a makefile.

**Comment by meisme-dev** [comment]
i cant run bat files on linux

**Comment by codingminecraft** [comment]
Yep, this code only works on windows right now. I made note of that in the README in the Build section. I plan on adding support for Linux, but I would like to implement more features before I add Linux support.
