### ISSUE TITLE
[suggestion] multiplayer

### ISSUE THREAD

**Issue by tomveich** [codingminecraft/StreamMinecraftClone#6]
Allow multiple players to play on the same world.

**Comment by codingminecraft** [comment]
Thanks for the suggestion tomveich! I've been meaning to do this, and I thought I had added it to the TODO in the README, but it looks like I missed that. I've added it to the TODO list and I'll be implementing it next :)

https://github.com/codingminecraft/StreamMinecraftClone#most-important
